### ISSUE TITLE
[BUG] figma-to-css return formated output 

### ISSUE THREAD

**Issue by pspaczek** [infermedica/component-library#122]
**Description**
stylelint can't anymore fix indent in css files; firma-to-css return output with strange formatting.
```scss
// Auto-generated file by update:css-variables script. Do not edit manually
html {--space-2: 0.125rem;
--space-4: 0.25rem;
--space-8: 0.5rem;
--space-12: 0.75rem;
--space-16: 1rem;
--space-20: 1.25rem;
--space-24: 1.5rem;
--space-32: 2rem;
--space-40: 2.5rem;
--space-48: 3rem;
--space-64: 4rem;
--space-96: 6rem;

--border-radius-button: 0.3125rem;
...
--opacity-medium: 0.5;}
```
**Expected**
We need content 
* without empty new lines 
* withe new line after `html {` and after last variable
* with expected indent 2 space
```scss
// Auto-generated file by update:css-variables script. Do not edit manually
html {
  --font-h1: var(--font-weight-default) var(--font-size-6) / var(--line-height-default) var(--font-family-heading);
  --font-h2: var(--font-weight-default) var(--font-size-4) / var(--line-height-default) var(--font-family-heading);
  --font-h3: var(--font-weight-default) var(--font-size-3) / var(--line-height-default) var(--font-family-heading);
  --font-h4: var(--font-weight-thick) var(--font-size-2) / var(--line-height-default) var(--font-family-heading);
  --font-h5: var(--font-weight-thick) var(--font-size-1) / var(--line-height-2) var(--font-family-heading);
    
  @media screen and (min-width: 768px) {
    --font-h1: var(--font-weight-default) var(--font-size-7) / var(--line-height-default) var(--font-family-heading);
    --font-h2: var(--font-weight-default) var(--font-size-5) / var(--line-height-default) var(--font-family-heading);
    --font-h3: var(--font-weight-default) var(--font-size-4) / var(--line-height-default) var(--font-family-heading);
  }
}
```
* update `update:css-variables` script to `"update:css-variables": "node --experimental-fetch scripts/figma-to-css.mjs",`
